// src/vue-echarts.vue
<template>
  <div ref="container">
  </div>
</template>
<script>
  import echarts from 'echarts'
  export default {
    props: ['option','loading'],

    mounted(){
      console.log(this.$refs.container)
      const width = document.documentElement.clientWidth
      this.$refs.container.style.width = `${width-20}px`
      this.$refs.container.style.height = `${(width -20) * 1.2}px`
      this.chart = echarts.init(this.$refs.container, 'dark')
      this.chart.setOption(this.option)
    },
    watch: {
      option(){
        console.log(this.option)
        this.chart.setOption(this.option)
      },
      loading(){
        if(this.loading){
          this.chart.showLoading()
        }else{
          this.chart.hideLoading()
        }
      }
    }
  }
</script>

// src/react-echarts.jsx
import React, {useEffect, useRef,props} from 'react'
import echarts from 'echarts'

export function ReactEcharts(props){
  const container = useRef(null)
  const chart = useRef(null)
  const {option,loading} = props
  useEffect(()=>{
    const width = document.documentElement.clientWidth
    container.current.style.width = `${width-20}px`
    container.current.style.height = `${(width -20) * 1.2}px`
    chart.current = echarts.init(container.current, 'dark')
  },[]) // mounted 第一次渲染, 空数组第一次渲染，不是空数组每次渲染

  useEffect(()=>{
    chart.current.setOption(option)
  },[option]) // when option changes
  useEffect(()=>{
    if(loading){
      chart.current.showLoading()
    }else{
      chart.current.hideLoading()
    }
  },[loading])
  return (<div ref={container}/>)
}
